//! The salt the session signing key is derived under (US-55, [ADR-0010]'s
//! 2026-09-19 amendment): random, generated by the server on first boot and
//! kept in the data directory, never sent anywhere. A leaked token is a
//! signature under a key nobody can reproduce without it, so it allows no
//! password guessing at all.
//!
//! It must survive restarts — a new salt is a new key, which signs the owner
//! out — so it is read back on every boot. One that cannot be read back is
//! replaced: that ends every session once and loses nothing else.
//!
//! [ADR-0010]: ../../../docs/adr/0010-single-user-optional-auth.md

use std::io::{self, Write};
use std::path::Path;

use crate::config::auth::SALT_LEN;

#[derive(Clone, PartialEq)]
pub struct Salt([u8; SALT_LEN]);

/// Never printed: with it, a leaked token becomes a way to guess the password.
impl std::fmt::Debug for Salt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Salt(..)")
    }
}

impl Salt {
    /// A fresh salt from the operating system's secure random source.
    pub fn generate() -> io::Result<Self> {
        let mut bytes = [0; SALT_LEN];
        getrandom::fill(&mut bytes).map_err(io::Error::other)?;
        Ok(Self(bytes))
    }

    /// The salt stored at `path`, or a new one stored there when there is
    /// none — or none that can be read back as a salt.
    pub fn load_or_create(path: &Path) -> io::Result<Self> {
        match std::fs::read(path) {
            Ok(bytes) => match <[u8; SALT_LEN]>::try_from(bytes.as_slice()) {
                Ok(salt) => return Ok(Self(salt)),
                Err(_) => tracing::warn!(
                    path = %path.display(),
                    len = bytes.len(),
                    "session salt has the wrong length; replacing it, which ends every session"
                ),
            },
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => tracing::warn!(
                path = %path.display(),
                error = %e,
                "session salt is unreadable; replacing it, which ends every session"
            ),
        }
        let salt = Self::generate()?;
        salt.store(path)?;
        Ok(salt)
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }

    /// Write the salt readable by its owner only, atomically: a crash
    /// mid-write leaves the old file or the new one, never half of either —
    /// and renaming over the old file works even when it cannot be read.
    fn store(&self, path: &Path) -> io::Result<()> {
        let dir = path.parent().unwrap_or(Path::new("."));
        // `tempfile` creates the file with mode 0600 on Unix.
        let mut file = tempfile::NamedTempFile::new_in(dir)?;
        file.write_all(&self.0)?;
        file.as_file().sync_all()?;
        file.persist(path).map_err(|e| e.error)?;
        Ok(())
    }
}

impl From<[u8; SALT_LEN]> for Salt {
    fn from(bytes: [u8; SALT_LEN]) -> Self {
        Self(bytes)
    }
}

// ── Tests (written first — ADR-0012) ─────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    fn salt_path(dir: &tempfile::TempDir) -> std::path::PathBuf {
        dir.path().join("session-salt")
    }

    #[test]
    fn us55_the_first_boot_creates_a_salt_only_its_owner_can_read() {
        let dir = tempfile::tempdir().unwrap();
        let path = salt_path(&dir);

        let salt = Salt::load_or_create(&path).unwrap();

        assert_eq!(std::fs::read(&path).unwrap(), salt.as_bytes());
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600, "mode {mode:o}");
    }

    #[test]
    fn us55_later_boots_reuse_the_stored_salt() {
        let dir = tempfile::tempdir().unwrap();
        let path = salt_path(&dir);

        let first = Salt::load_or_create(&path).unwrap();
        let second = Salt::load_or_create(&path).unwrap();

        assert_eq!(first, second);
    }

    #[test]
    fn us55_every_new_salt_is_different() {
        assert_ne!(Salt::generate().unwrap(), Salt::generate().unwrap());
    }

    #[test]
    fn us55_a_salt_of_the_wrong_length_is_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let path = salt_path(&dir);
        std::fs::write(&path, b"short").unwrap();

        let salt = Salt::load_or_create(&path).unwrap();

        assert_eq!(std::fs::read(&path).unwrap(), salt.as_bytes());
    }

    #[test]
    fn us55_an_unreadable_salt_is_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let path = salt_path(&dir);
        std::fs::write(&path, [1; SALT_LEN]).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();
        if std::fs::read(&path).is_ok() {
            // Running as root, where no file is unreadable: nothing to test.
            return;
        }

        let salt = Salt::load_or_create(&path).unwrap();

        assert_eq!(std::fs::read(&path).unwrap(), salt.as_bytes());
    }
}
